#!/usr/bin/env bash
set -u
f="$(dirname "$0")/../transcript-runner.md"
fail=0
need() { grep -qF -- "$1" "$f" && echo "ok   $1" || { echo "FAIL $1"; fail=1; }; }
need "# Transcript runner"
need "## 1. Inputs and outputs"
need "## 2. Operating rules"
need "## 3. Checkpoint protocol"
need "## 4. Local work folder"
need "tools/vtt-to-passages.sh"
need "Approve stage T"
need "work/transcripts/state.md"
need "## 5. Phases"
need "### T0. Register"
need "### T1. Passages and topics"
need "### T2. Classify"
need "### T3. Assemble claims"
need "### T4. Write claims"
need "## 6. Claim record"
need '"source_kind": "transcript"'
need "step-of"
need "retain no;"
need "## 7. Session summary"
need "## 8. Classification guide for passages"
need "1. **Consultant speaker?**"
need "3. **Explicit past or cessation?**"
need "4. **Commitment modal"
need "5. **Present tense plus stated redundancy?**"
need "## Appendix. Worked examples"
need "| Legacy beats current |"
need "| Split passage |"
need "two statements of different classes"
need "continue to step 7"
need "obligation within today's process"
need "| Obligation inside today's process |"
need "as many lettered parts as there are statements"
need "| Merged multi-sentence passage |"
need "| moscow |"
need "grep '^- Speaker:' | sort | uniq -c"
need "| Session | File | Meeting date | Stage | Status | Model | Mode | Last update |"
need "## Audit"
need "| Session | Stage | Model | Mode | Runner | Date | Passages | Claims | Questions raised | Class changed by human |"
need "version number from this document"
need "Record the model you are running as"
need "standard for Fable"
need "**Self-check.**"
need "| runner_model |"
need "## 9. Running this runner"
need "claude --model"
exit $fail
